### ISSUE TITLE
logging problem

### ISSUE THREAD

**Issue by alirezafour** [MehdiSaeedifar/IrisCms#1]
hi,
when I try login in your site out of your main page, after logging in, your site redirect me into home page
I like to see my last page I visited.
I's better I guess.

**Comment by MehdiSaeedifar** [comment]
Hi,
if you use the modal form instead the login page, you shoudnt have any problem.
i attach screen shot from modal from.
![capture](https://cloud.githubusercontent.com/assets/10070897/11531828/f1ea2dca-9914-11e5-9287-c8456c828010.PNG)
